use_frameworks!

platform :ios, '8.0'

target 'OwenMD5_Example' do
  pod 'OwenMD5', :path => '../'

  target 'OwenMD5_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
